from config import (
    date_to_day,
    MON, TUE, WED, THU, FRI, SAT, SUN,
    DAY, NIGHT,
    AUTO_SL
)

SOCIAL_LINKS = {
    "Fool": {
        "name": "S.E.E.S. (Fool)",
        "arcana": "Fool",
        "slot": DAY,
        "unlock_day": date_to_day(4, 18),
        "end_day": date_to_day(12, 31),
        "auto_rank": True,
        "ranks_needed": [0] * 10,
        "available_days": set(),
        "school_restricted": False,
        "stat_req": {},
        "prereq_sl": {},
    },
    "Magician": {
        "name": "Kenji Tomochika (Magician)",
        "arcana": "Magician",
        "slot": DAY,
        "unlock_day": date_to_day(4, 22),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, THU, FRI},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 1, 1, 1, 2, 2, 2, 1],
        "stat_req": {},
        "prereq_sl": {},
    },
    "Priestess": {
        "name": "Fuuka Yamagishi (Priestess)",
        "arcana": "Priestess",
        "slot": DAY,
        "unlock_day": date_to_day(6, 19),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, FRI, SAT},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 2, 2, 2, 2, 2, 2, 1],
        "stat_req": {"courage": 6},
        "prereq_sl": {"Fortune": 1},
    },
    "Empress": {
        "name": "Mitsuru Kirijo (Empress)",
        "arcana": "Empress",
        "slot": DAY,
        "unlock_day": date_to_day(11, 21),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        # Mon & Fri tersedia hanya sampai Des 24, sisanya Tue/Wed/Thu/Sat
        "available_days": {MON, TUE, WED, THU, FRI, SAT},
        "school_restricted": False,
        "ranks_needed": [0, 1, 2, 2, 2, 2, 2, 2, 2, 1],
        "stat_req": {"academics": 6},
        "prereq_sl": {},
    },
    "Emperor": {
        "name": "Hidetoshi Odagiri (Emperor)",
        "arcana": "Emperor",
        "slot": DAY,
        "unlock_day": date_to_day(4, 27),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, WED, FRI},
        "school_restricted": True,
        "ranks_needed": [0, 1, 1, 2, 1, 1, 1, 2, 1, 2],
        "stat_req": {},
        "prereq_sl": {},
    },
    "Hierophant": {
        "name": "Bunkichi & Mitsuko (Hierophant)",
        "arcana": "Hierophant",
        "slot": DAY,
        "unlock_day": date_to_day(4, 25),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, WED, THU, FRI, SAT, SUN},
        "school_restricted": False,
        "ranks_needed": [0, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {},
        "note": "Selamatkan Bunkichi sebelum 4 Oktober (korban Tartarus 12 Sep)",
    },
    "Lovers": {
        "name": "Yukari Takeba (Lovers)",
        "arcana": "Lovers",
        "slot": DAY,
        "unlock_day": date_to_day(7, 25),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, WED, THU, SAT},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 2, 1, 2, 2, 2, 2, 1],
        "stat_req": {"charm": 6},
        "prereq_sl": {},
    },
    "Chariot": {
        "name": "Kazushi Miyamoto (Chariot)",
        "arcana": "Chariot",
        "slot": DAY,
        "unlock_day": date_to_day(4, 23),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, TUE, THU, FRI},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 2, 2, 2, 2, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {},
    },
    "Justice": {
        "name": "Chihiro Fushimi (Justice)",
        "arcana": "Justice",
        "slot": DAY,
        "unlock_day": date_to_day(5, 7),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, THU, SAT},
        "school_restricted": True,
        "ranks_needed": [0, 2, 2, 2, 2, 2, 2, 2, 2, 1],
        "stat_req": {},
        "prereq_sl": {"Emperor": 1},
    },
    "Hermit": {
        "name": "Maya (Hermit)",
        "arcana": "Hermit",
        "slot": DAY,
        "unlock_day": date_to_day(4, 29),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        # Hanya Minggu + hari libur tertentu (lihat HERMIT_HOLIDAYS di config)
        "available_days": {SUN},
        "school_restricted": False,
        "ranks_needed": [0, 1, 2, 1, 2, 1, 2, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {},
        "also_holidays": True,
    },
    "Fortune": {
        "name": "Keisuke Hiraga (Fortune)",
        "arcana": "Fortune",
        "slot": DAY,
        "unlock_day": date_to_day(6, 17),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, WED, THU},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 2, 1, 2, 1, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {},
    },
    "Strength": {
        "name": "Yuko Nishiwaki (Strength)",
        "arcana": "Strength",
        "slot": DAY,
        "unlock_day": date_to_day(4, 24),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {WED, SAT},
        "school_restricted": True,
        "ranks_needed": [0, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {"Chariot": 2},
    },
    "HangedMan": {
        "name": "Maiko Oohashi (Hanged-Man)",
        "arcana": "HangedMan",
        "slot": DAY,
        "unlock_day": date_to_day(5, 6),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, WED, SAT},
        "school_restricted": False,
        "ranks_needed": [0, 1, 2, 1, 2, 2, 2, 2, 2, 2],
        "stat_req": {},
        "prereq_sl": {},
        "note": "Selamatkan Maiko sebelum 3 November (korban Tartarus 21 Okt)",
    },
    "Death": {
        "name": "Pharos (Death)",
        "arcana": "Death",
        "slot": DAY,
        "unlock_day": date_to_day(6, 12),
        "end_day": date_to_day(11, 4),
        "auto_rank": True,
        "ranks_needed": [0] * 10,
        "available_days": set(),
        "school_restricted": False,
        "stat_req": {},
        "prereq_sl": {},
    },
    "Temperance": {
        "name": "Bebe (Temperance)",
        "arcana": "Temperance",
        "slot": DAY,
        "unlock_day": date_to_day(5, 8),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, WED, FRI},
        "school_restricted": True,
        "ranks_needed": [0, 1, 2, 1, 2, 2, 1, 2, 2, 2],
        "stat_req": {"academics": 2},
        "prereq_sl": {"Hierophant": 3},
    },
    "Devil": {
        "name": "President Tanaka (Devil)",
        "arcana": "Devil",
        "slot": NIGHT,
        "unlock_day": date_to_day(5, 16),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {TUE, SAT},
        "school_restricted": False,
        # Devil auto rank up setiap sesi, 1 sesi per rank
        "ranks_needed": [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "stat_req": {"charm": 4},
        "prereq_sl": {"Hermit": 4},
    },
    "Tower": {
        "name": "Mutatsu (Tower)",
        "arcana": "Tower",
        "slot": NIGHT,
        "unlock_day": date_to_day(5, 23),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {THU, FRI, SAT, SUN},
        "school_restricted": False,
        "ranks_needed": [0, 1, 2, 2, 2, 2, 2, 2, 2, 1],
        "stat_req": {"courage": 2},
        "prereq_sl": {"Strength": 4},
    },
    "Star": {
        "name": "Mamoru Hayase (Star)",
        "arcana": "Star",
        "slot": DAY,
        "unlock_day": date_to_day(8, 5),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {WED, FRI, SUN},
        "school_restricted": False,
        "ranks_needed": [0, 1, 2, 2, 2, 2, 2, 2, 2, 1],
        "stat_req": {"courage": 4},
        "prereq_sl": {},
    },
    "Moon": {
        "name": "Nozomi Suemitsu (Moon)",
        "arcana": "Moon",
        "slot": DAY,
        "unlock_day": date_to_day(4, 28),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, TUE, WED, THU, FRI, SAT, SUN},
        "school_restricted": False,
        "ranks_needed": [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "stat_req": {"charm": 2},
        "prereq_sl": {"Magician": 3},
    },
    "Sun": {
        "name": "Akinari Kamiki (Sun)",
        "arcana": "Sun",
        "slot": DAY,
        "unlock_day": date_to_day(8, 9),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {SUN},
        "school_restricted": False,
        # Sun auto rank up setiap sesi
        "ranks_needed": [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        "stat_req": {"academics": 4},
        "prereq_sl": {"HangedMan": 3},
    },
    "Judgement": {
        "name": "Nyx Annihilation Team (Judgement)",
        "arcana": "Judgement",
        "slot": DAY,
        "unlock_day": date_to_day(12, 31),
        "end_day": date_to_day(1, 31),
        "auto_rank": True,
        "ranks_needed": [0] * 10,
        "available_days": set(),
        "school_restricted": False,
        "stat_req": {},
        "prereq_sl": {},
        "note": "Membutuhkan True Ending (biarkan Ryoji hidup)",
    },
    "Aeon": {
        "name": "Aigis (Aeon)",
        "arcana": "Aeon",
        "slot": DAY,
        "unlock_day": date_to_day(1, 8),
        "end_day": date_to_day(1, 30),
        "auto_rank": False,
        "available_days": {MON, TUE, WED, THU, FRI, SAT},
        "school_restricted": False,
        "ranks_needed": [0, 1, 1, 1, 1, 1, 1, 1, 2, 1],
        "stat_req": {},
        "prereq_sl": {},
    },
}
